# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

#google-ID: ''

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Work', path: 'menu', url: 'work.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}
#- {name: 'Test', path: 'menu', url: 'writing-new.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/mcox53'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/matthew-cox-a4178b124/'}
- {icon: 'envelope', link: 'mailto:matthew.cox@uconn.edu'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Related:'

post_date_prefix: 'Written on'

tag_page: '/tags/'